### ISSUE TITLE
Minor problems expected to be fixed

### ISSUE THREAD

**Issue by Neph0s** [THU-KEG/COPEN#1]
Hi, I'm quite interested in your work and would like to try your code. 
Your code is excellent. However, there is several problems that I have to fix before successfully running it.
1. Suggest adding mkdir task[1-3]/data in preprocessing 
2. According to README, the data is put in task[1-3]/data. However, in most of the py files for preprocessing and running, the path is task[1-3]/data/ood/
3. For data preprocessing of task2 probing, there is no such file given named data_processor_for_ppl.py. I tried using probing_data_processor.py instead.

**Comment by h-peng17** [comment]
Thanks for the suggestions! I will fix the bugs mentioned as soon as possible.
