### ISSUE TITLE
What files should be submitted to codalab and What does "mask_position" in probing means?

### ISSUE THREAD

**Issue by Neph0s** [THU-KEG/COPEN#2]
Hello, I would like to try my models in the probing settings.
However, it seems that the test sets are not labelled, so we can only submit to codalab.
I spent several hours studying how to generate a file to be submitted to codalab, and now I suppose files like answer-bert-base-uncased-probs.json are what we should submit. Is it right?
Also, I found that there are an argument named "mask_position", which is a value from [all, answer, concept], and these values yield corresponding files. I wonder what's the difference among these values.

**Comment by h-peng17** [comment]
1. I don't provide a submission script for probing now. I will provide the script this week. You can first try `finetuning` models and upload your results.
2. For different "mask_position", we use different masked positions to calculate the log prob of candidates. You can check the details in our paper (Table 8).

**Comment by h-peng17** [comment]
Thanks for your questions. I will provide more explanations in the readme and code this week.

**Comment by Neph0s** [comment]
Thanks very much.
